

package com.longkd.chatgpt_openai.open.dto.edit

import com.longkd.chatgpt_openai.open.dto.Usage

/**
 * A list of edits generated by GPT-3
 *
 * https://beta.openai.com/docs/api-reference/edits/create
 */
class EditResult {
    /**
     * The type of object returned, should be "edit"
     */
    var edit: String? = null

    /**
     * The creation time in epoch milliseconds.
     */
    var created: Long = 0

    /**
     * A list of generated edits.
     */
    var choices: List<EditChoice>? = null

    /**
     * The API usage for this request
     */
    var usage: Usage? = null
}