
package com.longkd.chatgpt_openai.open.dto.edit

/**
 * An edit generated by GPT-3
 *
 * https://beta.openai.com/docs/api-reference/edits/create
 */
class EditChoice {
    /**
     * The edited text.
     */
    var text: String? = null

    /**
     * This index of this completion in the returned list.
     */
    var index: Int? = null
}