

package com.longkd.chatgpt_openai.open.dto.completion

import com.google.gson.annotations.SerializedName

/**
 * A completion generated by GPT-3
 *
 * https://beta.openai.com/docs/api-reference/completions/create
 */
class CompletionChoice {
    /**
     * The generated text. Will include the prompt if [CompletionRequest.echo] is true
     */
    @SerializedName("text")
    var text: String? = null

    /**
     * This index of this completion in the returned list.
     */
    @SerializedName("index")
    var index: Int? = null

    /**
     * The log probabilities of the chosen tokens and the top [CompletionRequest.logprobs] tokens
     */
    @SerializedName("logprobs")
    var logprobs: LogProbResult? = null

    /**
     * The reason why GPT-3 stopped generating, for example "length".
     */
    @SerializedName("finish_reason")
    var finish_reason: String? = null
}